"""Prepare the oil-spill dataset and write the class-distribution report.

Runs the verify+extract step, then analyses the real extracted masks and writes
``docs/data_report.md`` with per-class pixel counts, imbalance ratios, and
per-split totals. Intended to be wired into ``make data``.

Usage
-----
    python scripts/make_data.py [--root DIR] [--no-verify] [--force]
"""

from __future__ import annotations

import argparse
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
from PIL import Image

from oilspill.data.dataset import _LABEL_EXT, _LABEL_SUBDIR, make_splits
from oilspill.data.extract import prepare_dataset
from oilspill.metrics import CLASS_NAMES, NUM_CLASSES, OIL_CLASS_INDEX

_REPO_ROOT = Path(__file__).resolve().parents[1]
_REPORT_PATH = _REPO_ROOT / "docs" / "data_report.md"


def _label_dir_for_split(root: Path, split: str) -> Path:
    """Label directory for a logical split (train/val live under train/)."""
    source = "test" if split == "test" else "train"
    return root / source / _LABEL_SUBDIR


def analyse_masks(root: Path, stems: list[str], split: str) -> dict[str, object]:
    """Aggregate per-class pixel counts and image-presence counts over ``stems``."""
    label_dir = _label_dir_for_split(root, split)
    pixel_counts = np.zeros(NUM_CLASSES, dtype=np.int64)
    images_with_class = np.zeros(NUM_CLASSES, dtype=np.int64)
    sizes: Counter[tuple[int, int]] = Counter()

    for stem in stems:
        with Image.open(label_dir / f"{stem}{_LABEL_EXT}") as msk:
            arr = np.asarray(msk.convert("L"), dtype=np.int64)
        sizes[arr.shape] += 1  # (H, W)
        counts = np.bincount(arr.reshape(-1), minlength=NUM_CLASSES)
        pixel_counts += counts[:NUM_CLASSES]
        images_with_class += (counts[:NUM_CLASSES] > 0).astype(np.int64)

    return {
        "n_images": len(stems),
        "pixel_counts": pixel_counts,
        "images_with_class": images_with_class,
        "sizes": sizes,
    }


def _fmt_int(n: int) -> str:
    return f"{n:,}"


def _pct(part: int, total: int) -> float:
    return 100.0 * part / total if total else 0.0


def build_report(root: Path) -> str:
    """Compute statistics over the real data and render the markdown report."""
    splits = make_splits(root)
    split_stems = {"train": splits.train, "val": splits.val, "test": splits.test}
    stats = {name: analyse_masks(root, stems, name) for name, stems in split_stems.items()}

    train_pixels: np.ndarray = stats["train"]["pixel_counts"]  # type: ignore[assignment]
    overall_pixels = sum(
        s["pixel_counts"]
        for s in stats.values()  # type: ignore[misc]
    )

    # Imbalance ratios relative to the most common class (computed on train).
    max_train = int(train_pixels.max())
    imbalance = [max_train / c if c else float("inf") for c in train_pixels]
    oil_fraction_train = _pct(int(train_pixels[OIL_CLASS_INDEX]), int(train_pixels.sum()))

    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []
    lines.append("# Dataset report")
    lines.append("")
    lines.append(
        "Generated by `scripts/make_data.py` over the extracted dataset at "
        "`data/datasets/oil_spill/`. All numbers below are computed from the real "
        "`labels_1D/` masks; re-run the script to regenerate."
    )
    lines.append("")
    lines.append(f"_Last generated: {now}_")
    lines.append("")

    # --- split sizes ---
    lines.append("## Split sizes")
    lines.append("")
    lines.append("| Split | Images |")
    lines.append("|-------|-------:|")
    for name in ("train", "val", "test"):
        lines.append(f"| {name} | {_fmt_int(int(stats[name]['n_images']))} |")  # type: ignore[arg-type]
    total_imgs = sum(int(s["n_images"]) for s in stats.values())  # type: ignore[arg-type]
    lines.append(f"| **total** | **{_fmt_int(total_imgs)}** |")
    lines.append("")
    lines.append(
        "The official dataset split is train=1002 / test=110. The **test** split "
        "is the untouched official test set. The **val** split is a deterministic "
        "15% carve-out of the official train split (fixed seed in "
        "`oilspill.data.dataset.DEFAULT_SPLIT_SEED`), leaving the remainder for "
        "**train**. The same seed always yields identical, pairwise-disjoint lists."
    )
    lines.append("")

    # --- image size stats ---
    lines.append("## Image size")
    lines.append("")
    all_sizes: Counter[tuple[int, int]] = Counter()
    for s in stats.values():
        all_sizes.update(s["sizes"])  # type: ignore[arg-type]
    for (h, w), n in sorted(all_sizes.items()):
        lines.append(f"- `{w}x{h}` (WxH): {_fmt_int(n)} masks")
    lines.append("")
    lines.append(
        "SAR images are stored as 3-channel RGB (a single SAR channel replicated). "
        "The loader keeps 3 channels so ImageNet-pretrained encoders can be used."
    )
    lines.append("")

    # --- per-class pixel distribution (train) ---
    lines.append("## Per-class pixel distribution (train split)")
    lines.append("")
    lines.append(
        "Pixel counts come from the integer `labels_1D` masks. Imbalance ratio is "
        "the most-common class's pixel count divided by the class's pixel count "
        "(1.0 = the majority class)."
    )
    lines.append("")
    lines.append("| ID | Class | Pixels | % of pixels | Images w/ class | Imbalance ratio |")
    lines.append("|----|-------|-------:|------------:|----------------:|----------------:|")
    train_total = int(train_pixels.sum())
    n_train = int(stats["train"]["n_images"])  # type: ignore[arg-type]
    images_with: np.ndarray = stats["train"]["images_with_class"]  # type: ignore[assignment]
    for i in range(NUM_CLASSES):
        ratio = imbalance[i]
        ratio_str = "1.0" if ratio == 1.0 else (f"{ratio:,.1f}" if ratio != float("inf") else "inf")
        lines.append(
            f"| {i} | {CLASS_NAMES[i]} | {_fmt_int(int(train_pixels[i]))} | "
            f"{_pct(int(train_pixels[i]), train_total):.3f}% | "
            f"{_fmt_int(int(images_with[i]))} / {n_train} | {ratio_str} |"
        )
    lines.append("")

    # --- overall (all splits) ---
    lines.append("## Per-class pixel distribution (all splits)")
    lines.append("")
    lines.append("| ID | Class | Pixels | % of pixels |")
    lines.append("|----|-------|-------:|------------:|")
    overall_total = int(overall_pixels.sum())
    for i in range(NUM_CLASSES):
        lines.append(
            f"| {i} | {CLASS_NAMES[i]} | {_fmt_int(int(overall_pixels[i]))} | "
            f"{_pct(int(overall_pixels[i]), overall_total):.3f}% |"
        )
    lines.append("")

    # --- key numbers ---
    oil_name = CLASS_NAMES[OIL_CLASS_INDEX]
    worst_ratio = max(r for r in imbalance if r != float("inf"))
    lines.append("## Key numbers")
    lines.append("")
    lines.append(
        f"- Oil-class (`{oil_name}`) fraction of train pixels: **{oil_fraction_train:.3f}%**."
    )
    lines.append(
        f"- Oil-class imbalance ratio (majority : oil): **{imbalance[OIL_CLASS_INDEX]:,.1f} : 1**."
    )
    lines.append(f"- Worst-case imbalance ratio across classes: **{worst_ratio:,.1f} : 1**.")
    lines.append("")

    # --- interpretation ---
    lines.append("## Interpretation: implications for the loss")
    lines.append("")
    lines.append(
        "The class distribution is heavily imbalanced: the sea-surface background "
        f"dominates while the headline `{oil_name}` class occupies a small fraction "
        "of pixels. A plain (unweighted) cross-entropy loss would be minimised by "
        "predicting mostly background and would under-segment oil, so it is not a "
        "good fit here."
    )
    lines.append("")
    lines.append(
        "These numbers motivate an imbalance-aware loss for the segmentation stage: "
        "class-weighted cross-entropy (e.g. inverse-frequency or effective-number "
        "weights derived from the table above), and/or a region-overlap loss such "
        "as Dice combined with Focal loss to focus learning on the rare oil and "
        "look-alike classes. The exact weights should be derived from the train "
        "pixel counts reported here. Selection and reporting are on oil-class IoU "
        "and recall (see `oilspill.metrics`), not pixel accuracy, precisely because "
        "of this imbalance."
    )
    lines.append("")

    # --- auxiliary classification dataset decision ---
    lines.append("## Auxiliary classification dataset: usefulness decision")
    lines.append("")
    lines.append(
        "**Decision: do NOT use the auxiliary classification dataset "
        "(`data/raw/oil_spill_classification_dataset.zip`) for training or "
        "evaluation in this project.**"
    )
    lines.append("")
    lines.append(
        "Rationale. Inspecting the archive shows it is not an independent dataset: "
        "it is the *same* MKLab oil-spill data re-organised into binary oil / "
        "no-oil folders. Its `train` split contains 791 `Images_Oil` + 211 "
        "`Images_No_Oil` = 1002 images and its `test` split 88 + 22 = 110 images, "
        "exactly matching the segmentation train (1002) and test (110) counts, with "
        "matching `img_XXXX` filename stems and identical `Labels_1D`/`Labels` "
        "folders. It therefore adds no new imagery."
    )
    lines.append("")
    lines.append("Consequences for the candidate uses:")
    lines.append("")
    lines.append(
        "- **Auxiliary classification pretraining of the encoder** would pretrain on "
        "the very images later used for segmentation training, with no held-out "
        "benefit and a real risk of leaking test images into pretraining (the "
        "classification `train` includes images that map to the segmentation set). "
        "Not worthwhile."
    )
    lines.append(
        "- **Extra evaluation set**: it is the same images and the same official "
        "split, so it provides no independent evaluation signal."
    )
    lines.append(
        "- **Hard-negative / look-alike mining**: the binary oil/no-oil label is "
        "coarser than the existing 5-class masks (which already separate Oil from "
        "Look-alike). The segmentation masks we already load are strictly more "
        "informative, so the binary split offers nothing extra here either."
    )
    lines.append("")
    lines.append(
        "If a future need arises for an image-level oil/no-oil signal, it can be "
        "derived directly from the segmentation masks already loaded (oil present "
        "iff the oil class appears), avoiding this redundant, leakage-prone archive."
    )
    lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Directory containing the oil_spill dataset folder (default: data/datasets/).",
    )
    parser.add_argument(
        "--no-verify",
        action="store_true",
        help="Skip SHA-256 verification of the archive before extraction.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-extract even if the dataset already appears present.",
    )
    args = parser.parse_args()

    dataset_root = prepare_dataset(root=args.root, verify=not args.no_verify, force=args.force)
    print(f"Dataset ready at: {dataset_root}")

    report = build_report(dataset_root)
    _REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"Wrote report: {_REPORT_PATH}")


if __name__ == "__main__":
    main()
